Update build-x86.yml

diff --git a/.github/workflows/build-x86.yml b/.github/workflows/build-x86.yml
--- a/.github/workflows/build-x86.yml
+++ b/.github/workflows/build-x86.yml
@@ -18,7 +18,7 @@ on:
   workflow_dispatch:
   schedule:
    - cron: 0 20 * * 4
-   #      分,时,日,月,星期。每周五 20时执行一次 (UTC时间)
+   #     分,时,日,月,周。每周五 20时执行一次 (UTC时间)
   
 env:
   FREE_DISK_SH: scripts/free_disk_space.sh
@@ -27,7 +27,6 @@ env:
   REPO_BRANCH: master
   CONFIG_FILE: configs/packages-x86.txt
   CONFIG_5G: configs/packages-5G.txt
-  CONFIG_STORAGE: configs/storage.txt
   SETTINGS_SH: scripts/init-settings.sh
   PACKAGES_SH: scripts/packages.sh
   INSTALL5G_SH: scripts/install-5G.sh
@@ -59,6 +58,7 @@ jobs:
         docker container prune -f
         sudo mkdir -p /workdir
         sudo chown $USER:$GROUPS /workdir
+
     - name: 检查空间使用情况1
       if: (!cancelled())
       run: df -hT
@@ -68,7 +68,7 @@ jobs:
       run: |
         git clone $REPO_URL --depth 1 -b $REPO_BRANCH openwrt
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
-        cd openwrt
+
     - name: 开启缓存
       uses: klever1988/cachewrtbuild@main
       with:
@@ -81,24 +81,26 @@ jobs:
         cd openwrt
         ./scripts/feeds update -a
         ./scripts/feeds install -a
-    - name: 执行脚本
+
+    - name: 导入补丁和配置 & 执行脚本
       run: |
+        [ -d files ] && mv files openwrt/files || echo "files not found"
+        [ -f $CONFIG_5G ] && cat $CONFIG_5G >> openwrt/.config
+        [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
         cd openwrt
         chmod +x $GITHUB_WORKSPACE/$INSTALL5G_SH && $GITHUB_WORKSPACE/$INSTALL5G_SH
         chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
         chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
         chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH
-    - name: 导入补丁和配置 & 下载文件
-      run: |
-        [ -d files ] && mv files openwrt/files || echo "files not found"
-        [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
-        [ -f $CONFIG_5G ] && cat $CONFIG_5G >> openwrt/.config
-        [ -f $CONFIG_STORAGE ] && cat $CONFIG_STORAGE >> openwrt/.config
-        cd openwrt
-        make defconfig
-        make download -j8 V=10
-        find dl -size -1024c -exec ls -l {} \;
-        find dl -size -1024c -exec rm -f {} \;
+
+    # - name: 下载文件
+    #   run: |
+    #     cd openwrt
+    #     make defconfig
+    #     make download -j8 V=10
+    #     find dl -size -1024c -exec ls -l {} \;
+    #     find dl -size -1024c -exec rm -f {} \;
+
     - name: 空间使用情况2
       if: (!cancelled())
       run: df -hT
@@ -107,40 +109,43 @@ jobs:
       id: mtools
       run: |
         cd openwrt
+        make defconfig
         echo -e "$(($(nproc)+1)) thread compile"
         make tools/compile -j$(($(nproc)+1)) || make tools/compile -j1 V=s
         make toolchain/compile -j$(($(nproc)+1)) || make toolchain/compile -j1 V=s
         echo "status=success" >> $GITHUB_OUTPUT
+
     - name: 空间使用情况3_1
       if: (!cancelled())
       run: df -hT
 
     - name: 清除工具链编译中间产物...
-      if: steps.mtools.outputs.status == 'success'
+      if: steps.mtools.outputs.status == 'success' && !cancelled()
       run: |
         cd openwrt
         rm -rf dl/*
-        rm -rf build_dir/host/*
         rm -rf build_dir/toolchain-*
+
     - name: 空间使用情况3_2
       if: (!cancelled())
       run: df -hT
 
     - name: 编译内核
       id: mkernel
-      if: steps.mtools.outputs.status == 'success'
+      if: steps.mtools.outputs.status == 'success' && !cancelled()
       run: |
         cd openwrt
         echo -e "$(($(nproc)+1)) thread compile"
         make target/linux/compile -j$(($(nproc)+1)) || make target/linux/compile -j1 V=s
         echo "status=success" >> $GITHUB_OUTPUT
+
     - name: 空间使用情况4
       if: (!cancelled())
       run: df -hT
 
     - name: 编译插件
       id: mpackage
-      if: steps.mkernel.outputs.status == 'success'
+      if: steps.mkernel.outputs.status == 'success' && !cancelled()
       run: |
         cd openwrt
         echo -e "$(($(nproc)+1)) thread compile"
@@ -148,24 +153,26 @@ jobs:
         make package/index
         make package/install -j$(nproc) || make package/install -j1 V=s
         echo "status=success" >> $GITHUB_OUTPUT
+
     - name: 空间使用情况5
       if: (!cancelled())
       run: df -hT
 
     - name: 清除插件编译文件
       id: cpackage
-      if: steps.mpackage.outputs.status == 'success'
+      if: steps.mpackage.outputs.status == 'success' && !cancelled()
       run: |
         cd openwrt
         rm -rf build_dir/target-*/host
         echo "status=success" >> $GITHUB_OUTPUT
+
     - name: 空间使用情况6
       if: (!cancelled())
       run: df -hT
 
     - name: 编译固件
       id: compile
-      if: steps.cpackage.outputs.status == 'success'
+      if: steps.cpackage.outputs.status == 'success' && !cancelled()
       run: |
         cd openwrt
         echo -e "$(($(nproc)+1)) thread compile"
@@ -173,6 +180,7 @@ jobs:
         make json_overview_image_info
         make checksum
         echo "status=success" >> $GITHUB_OUTPUT
+
     - name: 空间使用情况7
       if: (!cancelled())
       run: df -hT
@@ -196,6 +204,7 @@ jobs:
         rm -rf packages
         echo "FIRMWARE=$PWD" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT
+
     - name: 上传固件目录
       uses: actions/upload-artifact@main
       if: env.UPLOAD_FIRMWARE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
@@ -207,9 +216,10 @@ jobs:
       id: tag
       if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
       run: |
-        echo -e "❌ lede主线源码版本，当前是 X86-64 平台\n" >> release.txt
-        echo "release_tag=$(date +"%Y.%m.%d_X86")" >> $GITHUB_OUTPUT
+        echo -e " X86-64平台\n 主线源码\n ip地址 : 192.168.5.1" >> release.txt
+        echo "release_tag=$(date +"%Y.%m.%d_X86-64")" >> $GITHUB_OUTPUT
         echo "status=success" >> $GITHUB_OUTPUT
+
     - name: 上传固件到发布
       uses: softprops/action-gh-release@v2.0.4
       if: steps.tag.outputs.status == 'success' && !cancelled()
@@ -224,7 +234,7 @@ jobs:
       uses: dev-drprasad/delete-older-releases@v0.3.3
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
       with:
-        keep_latest: 10
+        keep_latest: 15
         delete_tags: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
