Update build-x86.yml

diff --git a/.github/workflows/build-x86.yml b/.github/workflows/build-x86.yml
--- a/.github/workflows/build-x86.yml
+++ b/.github/workflows/build-x86.yml
@@ -23,6 +23,7 @@ on:
 env:
   REPO_URL: https://github.com/coolsnowwolf/lede
   REPO_BRANCH: master
+  CONFIG_FILE: configs/packages-x86.txt
   FREE_DISK_SH: scripts/free_disk_space.sh
   ENV_SH: scripts/environment.sh
   SETTINGS_SH: scripts/init-settings.sh
@@ -75,24 +76,29 @@ jobs:
         mixkey: 'x86'
         prefix: ${{ github.workspace }}/openwrt
 
-    - name: 更新 & 安装 feeds & 执行脚本
+    - name: 安装 feeds
       run: |
         cd openwrt
-        ./scripts/feeds update -a && ./scripts/feeds update -a
-        ./scripts/feeds install -a && ./scripts/feeds install -a
-        chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
-        chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
-        chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH
+        ./scripts/feeds update -a
+        ./scripts/feeds install -a
 
     - name: 导入补丁和配置 & 下载文件
       run: |
-        [ -e files ] && mv files openwrt/files
-        cat configs/packages-x86.txt >> openwrt/.config
+        [ -d files ] && mv files openwrt/files || echo "files not found"
+        [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
         cd openwrt
         make defconfig
         make download -j8 V=10
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;
+
+    - name: 执行脚本
+      run: |
+        cd openwrt
+        chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
+        chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
+        chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH
+        make defconfig
 
     - name: 编译固件
       id: compile
@@ -155,12 +161,12 @@ jobs:
       uses: dev-drprasad/delete-older-releases@v0.3.3
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
       with:
-        keep_latest: 5
+        keep_latest: 10
         delete_tags: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: 删除以前工作流程
+    - name: 删除以前的工作流程
       uses: Mattraks/delete-workflow-runs@v2
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
